Remove exports statement and fail at compile time
This step fixes the previous error by restoring the _requires_ clause in
module `com.greetings`, but introduces an equivalent error by removing
the _exports_ clause from the `org.astro` module descriptor. The
resulting error message should be the same:

    $ ./step.sh
    ...
    src/com.greetings/com/greetings/Main.java:6: error:
        package org.astro does not exist
            Object name = org.astro.World.name();
                                   ^

See http://openjdk.java.net/projects/jigsaw/quick-start#missing