Remove requires statement and fail at compile time
This step demonstrates what happens when the _requires_ clause is
omitted from the `com.greetings` module declaration. Upon trying to
build the `com.greetings` module, compilation should fail, because
`javac` will no longer be able to resolve the `org.astro` package:

    $ ./step.sh
    ...
    src/com.greetings/com/greetings/Main.java:6: error:
        package org.astro does not exist
            Object name = org.astro.World.name();
                                   ^

See http://openjdk.java.net/projects/jigsaw/quick-start#missing